services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: sing
      POSTGRES_PASSWORD: sing
      POSTGRES_DB: sing
    ports:
      - 5432:5432
    volumes:
      - .tmp/db:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    environment:
      MP_DATABASE: /data/mailpit.db
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - .tmp/mailpit:/data
