/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/Button.vue')['default']
    copy: typeof import('./components/ui/WideSlider copy.vue')['default']
    Greet: typeof import('./components/Greet.vue')['default']
    IconButton: typeof import('./components/ui/IconButton.vue')['default']
    KeyHints: typeof import('./components/KeyHints.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    ModeCard: typeof import('./components/home/ModeCard.vue')['default']
    ModeSelector: typeof import('./components/home/ModeSelector.vue')['default']
    Notification: typeof import('./components/ui/notification/Notification.vue')['default']
    NotificationHandler: typeof import('./components/ui/notification/NotificationHandler.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
    WideButton: typeof import('./components/ui/WideButton.vue')['default']
    WideSelect: typeof import('./components/ui/WideSelect.vue')['default']
    WideSlider: typeof import('./components/ui/WideSlider.vue')['default']
  }
}
