/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/Button.vue')['default']
    Greet: typeof import('./components/Greet.vue')['default']
    KeyHints: typeof import('./components/KeyHints.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    Notification: typeof import('./components/ui/notification/Notification.vue')['default']
    NotificationHandler: typeof import('./components/ui/notification/NotificationHandler.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
  }
}
