// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "replaygain", input: string, result: number },
    mutations: never,
    subscriptions: never
};
