// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "microphones", input: never, result: Microphone[] } | 
        { key: "replaygain", input: string, result: number },
    mutations: never,
    subscriptions: never
};

export type Microphone = { name: string; channels: number; sample_rates: number[] }
