// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.vue')['default']
    Button: typeof import('./components/menu/Button.vue')['default']
    copy: typeof import('./components/menu/RangeInput copy.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    IconButton: typeof import('./components/menu/IconButton.vue')['default']
    KeyHints: typeof import('./components/menu/KeyHints.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    ListInput: typeof import('./components/menu/ListInput.vue')['default']
    ModeCard: typeof import('./components/menu/index/ModeCard.vue')['default']
    RangeInput: typeof import('./components/menu/RangeInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/menu/songs/Search.vue')['default']
    SongCard: typeof import('./components/menu/songs/SongCard.vue')['default']
    SongPlayer: typeof import('./components/SongPlayer.vue')['default']
    Songs: typeof import('./components/menu/songs.vue')['default']
    SongScroller: typeof import('./components/menu/songs/SongScroller.vue')['default']
    Test: typeof import('./components/menu/Test.vue')['default']
    Tester: typeof import('./components/menu/Tester.vue')['default']
    TitleBar: typeof import('./components/menu/TitleBar.vue')['default']
    WideButton: typeof import('./components/menu/WideButton.vue')['default']
  }
}
