// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/menu/Button.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    KeyHints: typeof import('./components/menu/KeyHints.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    ModeCard: typeof import('./components/menu/index/ModeCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
