name: Build Game

on:
  push:
    branches:
      - main
      - 'feature/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            { os: 'macos-latest', target: 'aarch64-apple-darwin' },
            { os: 'macos-latest', target: 'x86_64-apple-darwin' },
            { os: 'ubuntu-22.04', target: 'x86_64-unknown-linux-gnu' },
            { os: 'windows-latest', target: 'x86_64-pc-windows-msvc' },
          ]

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libglib2.0-dev

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './apps/game/src-tauri -> target'
          key: ${{ matrix.platform.target }}

      - name: Install dependencies
        run: bun install

      - name: Build the Tauri app
        id: tauri-build
        uses: tauri-apps/tauri-action@v0
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_APP_URL: ${{ vars.VITE_APP_URL }}
        with:
          projectPath: apps/game
          tauriScript: bun run tauri
          args: --target ${{ matrix.platform.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tuneperfect-${{ matrix.platform.os }}-${{ matrix.platform.target }}
          path: "${{ join(fromJSON(steps.tauri-build.outputs.artifactPaths), '\n') }}"
          if-no-files-found: error

